[package]
name = "rerecast"
description = "Rust port of recastnavigation"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
readme = { workspace = true }

[dependencies]
slotmap = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
glam = { workspace = true }
bitflags = { workspace = true }
tracing = { workspace = true }

bevy_reflect = { workspace = true, optional = true }
serde = { workspace = true, optional = true, features = ["derive"] }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[features]
default = []
serialize = ["dep:serde", "glam/serde", "slotmap/serde", "bitflags/serde"]
bevy_reflect = ["dep:bevy_reflect"]

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
